security:
    password_hashers:
        App\Entity\ClaimUser\AccountInformations:
            algorithm: auto
            cost: 12

    providers:
        app_user_provider:
            entity:
                class: App\Entity\ClaimUser\AccountInformations
                property: emailAddress  # Doit matcher le nom exact de la propriété
                manager_name: claim_user_db

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/auth/login 
            stateless: true
            json_login:
                check_path: /api/auth/login
                username_path: email  # Doit matcher le nom du champ dans le JSON
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                # success_handler: App\Security\CustomAuthenticationSuccessHandler
                # failure_handler: lexik_jwt_authentication.handler.authentication_failure
                failure_handler: App\Security\CustomAuthenticationFailureHandler
            provider: app_user_provider

        api:
            pattern: ^/api
            stateless: true
            jwt: ~
            provider: app_user_provider

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }