security:
    password_hashers:
        App\Entity\ClaimUser\AccountInformations:
            algorithm: auto
            cost: 12

    providers:
        app_user_provider:
            entity:
                class: App\Entity\ClaimUser\AccountInformations
                property: emailAddress  # Doit matcher le nom exact de la propriété
                manager_name: claim_user_db

    # le firewall gère la sécurisation    
    firewalls: 
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/auth/login 
            stateless: true
            json_login:
                check_path: /api/auth/login
                username_path: email  # Doit matcher le nom du champ dans le JSON
                password_path: password
                # success_handler: lexik_jwt_authentication.handler.authentication_success
                success_handler: App\Security\CustomAuthenticationSuccessHandler
                # failure_handler: lexik_jwt_authentication.handler.authentication_failure
                failure_handler: App\Security\CustomAuthenticationFailureHandler
            provider: app_user_provider

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            entry_point: jwt
            jwt: ~
            refresh_jwt:
                check_path: /api/token/refresh

    # l'access_control détermine les permissions d'accès aus URLs
    access_control:
        - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
        # toutes les routes sous /api demandent un token valide (access token) pour être accessibles
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }